package com.ascend.mavlab.simulation.failures

enum class FailureSeverity(val label: String) {
    Caution("Caution"),
    Warning("Warning"),
    Critical("Critical"),
}

data class FailureScenario(
    val id: String,
    val title: String,
    val severity: FailureSeverity,
    val description: String,
    val whatHappened: String,
    val whyItHappened: String,
    val telemetrySignature: List<String>,
    val operatorResponse: List<String>,
    val safetyLesson: String,
    val recoveryCondition: String,
    val affectedState: String,
    val logEventName: String,
    val learningGoal: String,
    val apply: (FailureInjector) -> Unit,
    val clear: (FailureInjector) -> Unit,
)

val FailureScenarios = listOf(
    FailureScenario(
        id = "gps_loss",
        title = "GPS Signal Lost",
        severity = FailureSeverity.Critical,
        description = "GPS is unavailable, so assisted position modes degrade to altitude hold.",
        whatHappened = "The navigation solution lost global position.",
        whyItHappened = "Satellite lock can be blocked by terrain, buildings, RF interference, or a receiver fault.",
        telemetrySignature = listOf("GPS fix drops to 0", "satellite count drops to 0", "AUTO/LOITER/GUIDED degrade to ALT_HOLD"),
        operatorResponse = listOf("Stop autonomous mission work", "hold altitude manually", "recover visual control or command RTL only after position is reliable"),
        safetyLesson = "Position modes are only as safe as the positioning source behind them.",
        recoveryCondition = "Reset failures or restore GPS before restarting AUTO, GUIDED, or LOITER.",
        affectedState = "gpsEnabled=false",
        logEventName = "failure_gps_loss",
        learningGoal = "Observe how autonomous flight depends on healthy positioning.",
        apply = { it.setGpsEnabled(false) },
        clear = { it.setGpsEnabled(true) },
    ),
    FailureScenario(
        id = "gps_drift",
        title = "GPS Drift",
        severity = FailureSeverity.Warning,
        description = "GPS noise is increased to simulate multipath around buildings.",
        whatHappened = "The position estimate wanders even while the drone is trying to hold still.",
        whyItHappened = "Reflected satellite paths and poor geometry can produce noisy fixes without a total GPS loss.",
        telemetrySignature = listOf("GPS remains locked", "local position wanders", "hold modes make small corrections"),
        operatorResponse = listOf("Avoid precise autonomous work", "increase clearance", "switch to manual/altitude control if drift grows"),
        safetyLesson = "A GPS lock is not enough; the quality of that lock matters.",
        recoveryCondition = "Reset failures or move to a clearer sky view.",
        affectedState = "gpsNoiseMultiplier=5x",
        logEventName = "failure_gps_drift",
        learningGoal = "See why noisy position data causes wandering in hold modes.",
        apply = { it.setGpsNoiseMultiplier(5f) },
        clear = { it.setGpsNoiseMultiplier(1f) },
    ),
    FailureScenario(
        id = "windy_day",
        title = "Wind Drift",
        severity = FailureSeverity.Warning,
        description = "A strong easterly wind with gusts pushes the aircraft off track.",
        whatHappened = "The vehicle is pushed sideways while the controller fights to stay on track.",
        whyItHappened = "Wind creates a persistent external disturbance and gusts reduce control margin.",
        telemetrySignature = listOf("ground track drifts", "controller commands sustained correction", "vehicle path bends downwind"),
        operatorResponse = listOf("increase standoff from obstacles", "reduce mission speed", "abort if drift exceeds clearance"),
        safetyLesson = "Navigation plans need wind margin, especially near obstacles and during landing.",
        recoveryCondition = "Reset failures or wait for wind to calm before precision mission work.",
        affectedState = "windSpeedMs=8, windDirectionDeg=90, windGustsMs=2",
        logEventName = "failure_wind_drift",
        learningGoal = "Watch the controller fight external disturbance.",
        apply = {
            it.setWindSpeedMs(8f)
            it.setWindDirectionDeg(90f)
            it.setWindGustsMs(2f)
        },
        clear = {
            it.setWindSpeedMs(0f)
            it.setWindDirectionDeg(0f)
            it.setWindGustsMs(0f)
        },
    ),
    FailureScenario(
        id = "motor_failure",
        title = "Motor Weakness",
        severity = FailureSeverity.Critical,
        description = "Motor 3 loses thrust authority and the aircraft becomes hard to stabilize.",
        whatHappened = "One propulsion corner cannot produce commanded thrust.",
        whyItHappened = "A damaged propeller, ESC issue, overheated motor, or blocked rotor can reduce thrust.",
        telemetrySignature = listOf("motor 3 RPM collapses", "attitude corrections grow", "aircraft visual state enters failure"),
        operatorResponse = listOf("land immediately if controllable", "avoid aggressive stick inputs", "disarm only after touchdown"),
        safetyLesson = "Small quadcopters have little practical motor redundancy.",
        recoveryCondition = "Reset failures after landing and inspect the propulsion system before relaunch.",
        affectedState = "motorFailureMask includes motor 3",
        logEventName = "failure_motor_weakness",
        learningGoal = "Understand why quadcopters have limited motor redundancy.",
        apply = { it.setMotorFailed(index = 2, failed = true) },
        clear = { it.setMotorFailed(index = 2, failed = false) },
    ),
    FailureScenario(
        id = "battery_low",
        title = "Low Battery",
        severity = FailureSeverity.Warning,
        description = "Battery drain is accelerated until the RTL failsafe triggers.",
        whatHappened = "The battery estimate drops faster than expected.",
        whyItHappened = "Cold packs, old cells, high throttle, or payload drag can reduce useful capacity.",
        telemetrySignature = listOf("battery percentage declines quickly", "current draw is elevated", "RTL triggers near 20 percent"),
        operatorResponse = listOf("stop extending the mission", "return while reserve remains", "prepare for early landing"),
        safetyLesson = "Low-battery action must happen before the pack reaches critical voltage.",
        recoveryCondition = "Reset failures and recharge or replace the battery.",
        affectedState = "batteryDrainMultiplier=8x",
        logEventName = "failure_low_battery",
        learningGoal = "Observe low-battery failsafe behavior.",
        apply = { it.setBatteryDrainMultiplier(8f) },
        clear = { it.setBatteryDrainMultiplier(1f) },
    ),
    FailureScenario(
        id = "battery_critical",
        title = "Critical Battery",
        severity = FailureSeverity.Critical,
        description = "Battery drain becomes severe enough to make continued flight unsafe.",
        whatHappened = "Reserve is nearly gone and voltage sag threatens controlled landing.",
        whyItHappened = "The mission consumed reserve or the pack cannot supply expected current.",
        telemetrySignature = listOf("battery drops toward critical", "RTL or LAND becomes urgent", "available current margin shrinks"),
        operatorResponse = listOf("land at the nearest safe point", "cancel mission objectives", "do not continue to another waypoint"),
        safetyLesson = "Critical battery is a land-now condition, not a return-and-continue condition.",
        recoveryCondition = "Reset failures after the aircraft is safe on the ground.",
        affectedState = "batteryDrainMultiplier=15x",
        logEventName = "failure_critical_battery",
        learningGoal = "Practice treating battery critical as an immediate landing decision.",
        apply = { it.setBatteryDrainMultiplier(15f) },
        clear = { it.setBatteryDrainMultiplier(1f) },
    ),
    FailureScenario(
        id = "compass_interference",
        title = "Compass Interference",
        severity = FailureSeverity.Warning,
        description = "Heading is offset by nearby magnetic interference.",
        whatHappened = "The reported heading no longer matches the aircraft's real yaw.",
        whyItHappened = "Magnets, current loops, steel structures, or calibration errors can bias heading.",
        telemetrySignature = listOf("heading is offset", "navigation corrections point the wrong way", "mission path bends or oscillates"),
        operatorResponse = listOf("switch out of position navigation if it diverges", "move away from interference", "recalibrate before mission work"),
        safetyLesson = "Bad heading can make a valid GPS position unsafe for navigation.",
        recoveryCondition = "Reset failures or remove the interference and recalibrate.",
        affectedState = "compassOffsetDeg=45",
        logEventName = "failure_compass_interference",
        learningGoal = "See how bad heading data degrades navigation.",
        apply = { it.setCompassOffsetDeg(45f) },
        clear = { it.setCompassOffsetDeg(0f) },
    ),
    FailureScenario(
        id = "heavy_payload",
        title = "Payload Overweight",
        severity = FailureSeverity.Warning,
        description = "Adds mass so climb response and battery life degrade.",
        whatHappened = "The aircraft has less climb margin and consumes more current.",
        whyItHappened = "Payload mass increases thrust demand and reduces control reserve.",
        telemetrySignature = listOf("slower climb response", "higher current draw", "battery drains faster under throttle"),
        operatorResponse = listOf("reduce mission aggression", "increase takeoff and landing margin", "remove payload if climb response is poor"),
        safetyLesson = "Payload planning is part of flight safety, not only performance tuning.",
        recoveryCondition = "Reset failures or reduce payload before the next takeoff.",
        affectedState = "payloadMassKg=1",
        logEventName = "failure_payload_overweight",
        learningGoal = "Relate payload mass to thrust margin.",
        apply = { it.setPayloadMassKg(1f) },
        clear = { it.setPayloadMassKg(0f) },
    ),
    FailureScenario(
        id = "lost_link",
        title = "Lost Link",
        severity = FailureSeverity.Critical,
        description = "The command link is considered unavailable while the vehicle keeps its current autonomous state.",
        whatHappened = "Operator command authority is no longer reliable.",
        whyItHappened = "Radio range, antenna orientation, interference, or GCS shutdown can break the link.",
        telemetrySignature = listOf("lost-link warning active", "operator commands should be treated as unavailable", "mission status remains visible locally"),
        operatorResponse = listOf("let configured failsafe behavior proceed", "avoid conflicting manual commands", "re-establish link before resuming mission work"),
        safetyLesson = "A mission must be safe even when the operator cannot command every second.",
        recoveryCondition = "Reset failures after the GCS link is restored.",
        affectedState = "lostLinkActive=true",
        logEventName = "failure_lost_link",
        learningGoal = "Understand why autonomous failsafe planning matters before launch.",
        apply = { it.setLostLinkActive(true) },
        clear = { it.setLostLinkActive(false) },
    ),
    FailureScenario(
        id = "barometer_issue",
        title = "Barometer Issue",
        severity = FailureSeverity.Warning,
        description = "Altitude sensing is biased, which can make vertical decisions unreliable.",
        whatHappened = "The altitude estimate carries a fixed pressure-sensor bias.",
        whyItHappened = "Prop wash, pressure changes, blocked vents, or sensor drift can bias barometer readings.",
        telemetrySignature = listOf("altitude reads offset from expected", "vertical controller targets feel inconsistent", "mission altitude margin is harder to trust"),
        operatorResponse = listOf("increase vertical clearance", "avoid low-altitude autonomous segments", "land and recalibrate if the offset persists"),
        safetyLesson = "Altitude errors are most dangerous close to the ground or obstacles.",
        recoveryCondition = "Reset failures or recalibrate the altitude source before low-level work.",
        affectedState = "barometerOffsetMeters=3",
        logEventName = "failure_barometer_issue",
        learningGoal = "Connect pressure-sensor errors to altitude safety margins.",
        apply = { it.setBarometerOffsetMeters(3f) },
        clear = { it.setBarometerOffsetMeters(0f) },
    ),
    FailureScenario(
        id = "unsafe_mission_reserve",
        title = "Unsafe Mission Reserve",
        severity = FailureSeverity.Critical,
        description = "The loaded mission is treated as consuming more reserve than the aircraft should spend.",
        whatHappened = "The mission plan no longer leaves a safe return or landing margin.",
        whyItHappened = "Long routes, high speed, wind, payload, or low starting battery can exhaust reserve.",
        telemetrySignature = listOf("mission reserve warning active", "battery drain is elevated", "Mission tab flags the route as unsafe"),
        operatorResponse = listOf("do not start AUTO", "shorten the route or recharge", "keep a nearby landing option"),
        safetyLesson = "A mission can be unsafe before the aircraft ever leaves the ground.",
        recoveryCondition = "Reset failures after route reserve is corrected.",
        affectedState = "unsafeMissionReserveActive=true, batteryDrainMultiplier=4x",
        logEventName = "failure_unsafe_mission_reserve",
        learningGoal = "Practice rejecting a mission that lacks return and landing reserve.",
        apply = {
            it.setUnsafeMissionReserveActive(true)
            it.setBatteryDrainMultiplier(4f)
        },
        clear = {
            it.setUnsafeMissionReserveActive(false)
            it.setBatteryDrainMultiplier(1f)
        },
    ),
)
